name: Cypress Tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-percy-test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest-4-cores
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          wait-on: 'https://stage.visualcomfort.com'
          wait-on-timeout: 120
          config: baseUrl=https://stage.visualcomfort.com
          working-directory: tests/cypress
          command: npx percy exec -- cypress run --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}