name: Cypress Tests production
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-percy-test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - run: cd tests && npm i

      - run: cd tests && npm run production
